services:
    database:
        image: mongo:7.0
        container_name: database
        environment:
            # - MONGO_INITDB_ROOT_USERNAME=admin
            # - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=chess_center
        command: --wiredTigerCacheSizeGB 1.5
        ports: 
            - 27017:27017
        restart: always