services:
    database:
        image: mongo:7.0
        container_name: database
        environment:
        # - MONGO_INITDB_ROOT_USERNAME=admin
        # - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=chess_center
        command: --wiredTigerCacheSizeGB 1.5
        ports:
        - 27017:27017
        restart: always

    # docker build . -t api
    api:
        image: api
        container_name: api
        depends_on:
            - database
        ports:
            - 3000:3000
        restart: always

    # docker build . -t app
    app:
        image: app
        container_name: app
        depends_on:
            - api
        ports:
            - 3001:3000
        restart: always
